//! The `plog!` family.
//!
//! Each macro checks [`LogFilterConfig`] first and only then delegates to the
//! matching `bevy::log` macro with the category as its `target:`. Because the
//! format arguments live inside the `if`, a suppressed call site costs one hash
//! lookup plus a branch and never touches `format_args!`.
//!
//! Both a global and an entity-scoped form exist:
//!
//! ```ignore
//! pwarn!(log, LogCat::World, "scenario {path} missing");
//! pdebug!(log, LogCat::Admit, entity = ship, "rejected {system:?}");
//! ```
//!
//! `$cfg` may be a `Res<LogFilterConfig>`, a `&LogFilterConfig`, or the value
//! itself — it is only ever used through auto-deref.

/// Shared gate. Not called directly; use the level aliases below.
#[doc(hidden)]
#[macro_export]
macro_rules! __plog_gated {
    // Entity-scoped: both the category level and the entity allow-list apply.
    ($cfg:expr, $cat:expr, $level:expr, $emit:ident, entity = $entity:expr, $($arg:tt)*) => {{
        let __cfg = $crate::logging::AsLogFilter::log_filter(&$cfg);
        if __cfg.cat_enabled($cat, $level) && __cfg.entity_allowed($entity) {
            ::bevy::log::$emit!(target: $cat.target(), $($arg)*);
        }
    }};
    // Global: category level only. Always passes the entity filter, because an
    // event with no entity has nothing to filter on.
    ($cfg:expr, $cat:expr, $level:expr, $emit:ident, $($arg:tt)*) => {{
        let __cfg = $crate::logging::AsLogFilter::log_filter(&$cfg);
        if __cfg.cat_enabled($cat, $level) {
            ::bevy::log::$emit!(target: $cat.target(), $($arg)*);
        }
    }};
}

// The five level aliases. Written out rather than generated by a
// macro-defining-macro: nesting `macro_rules!` requires escaping every inner
// `$`, which makes the definition far harder to read than the repetition it
// saves. In each pair the entity arm must come first, otherwise the global arm
// would match `entity = ...` as the start of the format arguments.

/// Category-filtered `error!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! perror {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Error, error, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Error, error, $($arg)*)
    };
}

/// Category-filtered `warn!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! pwarn {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Warn, warn, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Warn, warn, $($arg)*)
    };
}

/// Category-filtered `info!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! pinfo {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Info, info, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Info, info, $($arg)*)
    };
}

/// Category-filtered `debug!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! pdebug {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Debug, debug, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Debug, debug, $($arg)*)
    };
}

/// Category-filtered `trace!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! ptrace {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Trace, trace, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Trace, trace, $($arg)*)
    };
}

#[cfg(test)]
mod tests {
    use crate::logging::{EntityFilter, LevelFilter, LogCat, LogFilterConfig};
    use bevy::prelude::*;

    /// The macros must accept a bare `LogFilterConfig`, a reference, and a
    /// `Res<_>` without the call site caring which it has.
    #[test]
    fn macros_expand_over_value_reference_and_res() {
        let cfg = LogFilterConfig {
            default_level: LevelFilter::Trace,
            ..Default::default()
        };
        let e = Entity::from_raw_u32(1).unwrap();

        pwarn!(cfg, LogCat::World, "by value {}", 1);
        let by_ref = &cfg;
        pinfo!(by_ref, LogCat::Ai, "by reference");
        pdebug!(cfg, LogCat::Admit, entity = e, "entity-scoped {}", 2);
        ptrace!(cfg, LogCat::Physics, "trace");
        perror!(cfg, LogCat::Config, entity = e, "error");
    }

    // Note on what is *not* tested here: whether a suppressed call site skips
    // evaluating its format arguments. Under `cargo test` no `tracing`
    // subscriber is installed, so `tracing` short-circuits every event on its
    // own — a side-effect probe in the format args never runs regardless of
    // what this module's gate decides, and such a test would pass vacuously.
    // The gate itself is covered directly by the `cat_enabled` /
    // `entity_allowed` tests in `filter.rs`; what remains for the macros is
    // that they expand correctly and route to the right predicates, below.

    /// The trap this design exists to avoid: a system that logs must still run
    /// in a bare `App` that never inserted `LogFilterConfig`. Before
    /// `AsLogFilter`, adding one `plog!` to a shared system broke 430 existing
    /// tests at parameter validation.
    #[test]
    fn a_logging_system_runs_without_the_resource_inserted() {
        fn logs_things(log: Option<Res<LogFilterConfig>>) {
            pwarn!(log, LogCat::World, "still runs with no resource");
        }
        let mut app = App::new();
        app.add_systems(Update, logs_things);
        app.update(); // Would panic on `Res<LogFilterConfig>`.
    }

    /// And it must pick up a real config when one *is* present.
    #[test]
    fn the_resource_is_used_when_present() {
        fn assert_trace_enabled(log: Option<Res<LogFilterConfig>>) {
            let cfg = crate::logging::AsLogFilter::log_filter(&log);
            assert_eq!(cfg.default_level, LevelFilter::Trace);
        }
        let mut app = App::new();
        app.insert_resource(LogFilterConfig {
            default_level: LevelFilter::Trace,
            ..Default::default()
        });
        app.add_systems(Update, assert_trace_enabled);
        app.update();
    }

    /// Both forms must consult the predicates the macro claims to. Mirrors the
    /// exact expressions `__plog_gated!` expands to.
    #[test]
    fn gate_predicates_match_the_documented_semantics() {
        let cfg = LogFilterConfig {
            default_level: LevelFilter::Trace,
            entity_filter: Some(EntityFilter::new(vec!["Ironveil".into()])),
            ..Default::default()
        };
        let unresolved = Entity::from_raw_u32(9).unwrap();

        // Entity form: category passes, entity does not, so the event is out.
        assert!(cfg.cat_enabled(LogCat::Ai, LevelFilter::Debug));
        assert!(!cfg.entity_allowed(unresolved));

        // Global form checks only the category, so an entity filter must not
        // swallow entity-less events.
        assert!(cfg.cat_enabled(LogCat::Ai, LevelFilter::Debug));
    }
}
