// AUTO-GENERATED by scripts/wasm-editor-alias.mjs (Trunk post_build, issue #995).
// Stable editor entry re-exporting the content-hashed wasm-bindgen glue.
// Do not edit by hand; regenerated on every build.
import init from './project-phoenix-6422a40f67bddda2.js';

// Named exports: wasm_get_script_host_fns, wasm_script_diagnostics, initSync, …
export * from './project-phoenix-6422a40f67bddda2.js';

// wasm-bindgen's default init() fetches the UN-hashed _bg.wasm relative to the
// glue's URL; bind the hashed path so the editor's argument-less mod.default()
// finds the file trunk actually emitted.
const WASM_URL = new URL('./project-phoenix-6422a40f67bddda2_bg.wasm', import.meta.url);

export default function initPhoenixEditor(opts) {
  return init(opts ?? { module_or_path: WASM_URL });
}
