[build]
target = "server.html"
dist = "dist"
public_url = "./"

[[copy_file]]
source = "assets/"
destination = "assets/"

[[copy_file]]
source = "client/"
destination = "client/"

[watch]
watch_path = ["assets/", "client/"]
include = "*.toml"
