[base]
offset = [ 0, -0.2, 0 ]
rotation = [ 0, 0, 0 ]
scale = [ 4, 4, 4 ]

[extents]
min = [ -3.7817976474761963, -0.2, -3.7996280193328857 ]
max = [ 3.780076742172241, 3.1662600517272947, 3.79475998878479 ]
size = [ 7.5618743896484375, 3.366260051727295, 7.594388008117676 ]

[markers]

[[lod]]
max_distance = 15.0
model = "assets/models/alliance_research_outpost.glb"

[[lod]]
max_distance = 100.0
model = "assets/models/alliance_research_outpost_lod1.glb"

[lod.generate]
source = "assets/models/alliance_research_outpost.glb"
ratio = 0.95
error = 0.01
texture_size = 512
remesh_voxel_size = 0.0211

[[lod]]
max_distance = 400.0
model = "assets/models/alliance_research_outpost_lod2.glb"

[lod.generate]
source = "assets/models/alliance_research_outpost.glb"
ratio = 0.25
error = 0.01
texture_size = 128
remesh_voxel_size = 0.0211

[[lod]]
billboard = "assets/models/alliance_research_outpost_lod3.png"
scale = [ 7.5944, 3.3662, 1.0 ]

[lod.capture]
source = "assets/models/alliance_research_outpost.glb"
yaw_views = 8
resolution = 256
pitch = 20.0
