[base]
offset = [ 0, -0.2, 0.1 ]
rotation = [ 0, 3.14, 0 ]
scale = [ 1, 1, 1 ]

[extents]
min = [ -4.000085809088489, -0.428268851928259, -3.9000858090884902 ]
max = [ 4.000085809088489, 0.3531023304182314, 4.1000858090884895 ]
size = [ 8.000171618176978, 0.7813711823464904, 8.00017161817698 ]

[markers.phasers_fore]
position = [ 0, -0.12826885043814285, 1 ]
direction = [ 0, 0, 1 ]

[markers.phasers_aft]
position = [ 0.00021405124331257193, 0.4531023289281153, -0.8656009921424426 ]
direction = [ 0, 0, -1 ]

[markers.engine_port]
position = [ -0.8, 0.1, -0.9 ]
direction = [ 0, 0, -1 ]

[markers.engine_starboard]
position = [ 0.8, 0.1, -0.9 ]
direction = [ 0, 0, -1 ]

[markers.torpedo_aft]
position = [ 0, 0, -0.7 ]
direction = [ 0, 0, -1 ]

[markers.torpedo_port]
position = [ 0.25, 0, 0.25 ]
direction = [ 0.1389302994421039, 0, 0.9903021619167189 ]

[markers.torpedo_starboard]
position = [ -0.25, 0, 0.25 ]
direction = [ -0.13938093999218928, 0, 0.9902388366282621 ]

[markers.camera_fore]
position = [ 0, 0, 1 ]
direction = [ 0, 0, 1 ]

[markers.camera_aft]
position = [ 0, 0, -1 ]
direction = [ 0, 0, -1 ]

[markers.camera_port]
position = [ 1, 0, 0 ]
direction = [ 1, 0, 0 ]

[markers.camera_starboard]
position = [ -1, 0, 0 ]
direction = [ -1, 0, 0 ]

[[lod]]
max_distance = 15.0
model = "assets/models/alliance_cruiser.glb"

[[lod]]
max_distance = 100.0
model = "assets/models/alliance_cruiser_lod1.glb"

[lod.generate]
source = "assets/models/alliance_cruiser.glb"
ratio = 0.95
error = 0.01
texture_size = 512
remesh_voxel_size = 0.0211

[[lod]]
max_distance = 400.0
model = "assets/models/alliance_cruiser_lod2.glb"

[lod.generate]
source = "assets/models/alliance_cruiser.glb"
ratio = 0.15
error = 0.01
texture_size = 256
remesh_voxel_size = 0.0211

[[lod]]
billboard = "assets/models/alliance_cruiser_lod3.png"
scale = [ 1.9019, 0.4357, 1.0 ]

[lod.capture]
source = "assets/models/alliance_cruiser.glb"
yaw_views = 8
resolution = 256
pitch = 20.0
