[base]
offset = [ 0, -0.2, 0 ]
rotation = [ 0, 0, 0 ]
scale = [ 5, 6, 6 ]

[extents]
min = [ -4.742095768451691, -0.2, -5.68436872959137 ]
max = [ 4.7441565990448, 4.575006532669067, 5.67728054523468 ]
size = [ 9.48625236749649, 4.775006532669067, 11.36164927482605 ]

[markers]

[[lod]]
max_distance = 15.0
model = "assets/models/alliance_starbase.glb"

[[lod]]
max_distance = 100.0
model = "assets/models/alliance_starbase_lod1.glb"

[lod.generate]
source = "assets/models/alliance_starbase.glb"
ratio = 0.95
error = 0.01
texture_size = 512
remesh_voxel_size = 0.0211

[[lod]]
max_distance = 400.0
model = "assets/models/alliance_starbase_lod2.glb"

[lod.generate]
source = "assets/models/alliance_starbase.glb"
ratio = 0.15
error = 0.01
texture_size = 256
remesh_voxel_size = 0.0211

[[lod]]
shape = "sphere"
colour = [ 0.4713, 0.5171, 0.5851 ]
radius = 4.7431
scale = [ 1.0, 0.5034, 1.1977 ]
