[base]
offset = [ 0, -0.1, 0.2 ]
rotation = [ 0, 3.14, 0 ]
scale = [ 0.75, 0.75, 0.75 ]

[extents]
min = [ -0.7124516218446484, -0.1, -0.5042907575195503 ]
max = [ 0.712478993161924, 0.2415822461247444, 0.9073702938917316 ]
size = [ 1.4249306150065724, 0.3415822461247444, 1.411661051411282 ]

[[target_points]]
position = [ 0.5, -0.1, 0 ]

[[target_points]]
position = [ -0.25, -0.1, 0.25 ]

[[target_points]]
position = [ -0.25, -0.1, -0.25 ]

[markers.engine_port]
position = [ -0.25, 0.0, 0.78 ]
direction = [ 0, 0, 1 ]

[markers.engine_starboard]
position = [ 0.25, 0.0, 0.78 ]
direction = [ 0, 0, 1 ]

[[lod]]
max_distance = 15.0
model = "assets/models/dynasty_courier.glb"

[[lod]]
max_distance = 100.0
model = "assets/models/dynasty_courier_lod1.glb"

[lod.generate]
source = "assets/models/dynasty_courier.glb"
ratio = 0.95
error = 0.01
texture_size = 512
remesh_voxel_size = 0.0211

[[lod]]
max_distance = 400.0
model = "assets/models/dynasty_courier_lod2.glb"

[lod.generate]
source = "assets/models/dynasty_courier.glb"
ratio = 0.25
error = 0.01
texture_size = 256
remesh_voxel_size = 0.0211

[[lod]]
billboard = "assets/models/dynasty_courier_lod3.png"
scale = [ 1.4249, 0.3416, 1.0 ]

[lod.capture]
source = "assets/models/dynasty_courier.glb"
yaw_views = 8
resolution = 256
pitch = 20.0
