[base]
offset = [ 0, -0.3, 0.2 ]
rotation = [ 0, 3.14, 0 ]
scale = [ 2, 2, 2 ]

[extents]
min = [ -1.9011206581177087, -0.3, -1.7000550403194616 ]
max = [ 1.9015838440234958, 1.0864595890045166, 2.0442562229928125 ]
size = [ 3.8027045021412045, 1.3864595890045166, 3.744311263312274 ]

[[target_points]]
position = [ 0.5, -0.1, 0 ]

[[target_points]]
position = [ -0.25, -0.1, 0.25 ]

[[target_points]]
position = [ -0.25, -0.1, -0.25 ]

[markers.engine_port]
position = [ -1.05, 0.0, 1.85 ]
direction = [ 0, 0, 1 ]

[markers.engine_starboard]
position = [ 1.05, 0.0, 1.85 ]
direction = [ 0, 0, 1 ]

[[lod]]
max_distance = 15.0
model = "assets/models/dynasty_battleship.glb"

[[lod]]
max_distance = 100.0
model = "assets/models/dynasty_battleship_lod1.glb"
tier_rig = "identity"

[lod.generate]
source = "assets/models/dynasty_battleship.glb"
ratio = 0.536
error = 0.01
texture_size = 512
remesh_voxel_size = 0.0211

[[lod]]
max_distance = 400.0
model = "assets/models/dynasty_battleship_lod2.glb"
tier_rig = "identity"

[lod.generate]
source = "assets/models/dynasty_battleship.glb"
ratio = 0.113
error = 0.01
texture_size = 128
remesh_voxel_size = 0.0211

[[lod]]
billboard = "assets/models/dynasty_battleship_lod3.png"
scale = [ 3.8027, 1.3865, 1.0 ]

[lod.capture]
source = "assets/models/dynasty_battleship.glb"
yaw_views = 8
resolution = 256
pitch = 20.0
