[package]
name = "phoenix-content"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[features]
test-support = []

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
vellum-digest = { workspace = true }
toml = "1.0"
phoenix-model = { path = "../phoenix-model" }
gltf = { version = "1.4.1", default-features = false, features = ["utils", "extras", "names", "extensions"] }
ktx2 = "0.4.0"
bevy_image = { version = "0.18.1", features = ["webp", "png", "jpeg", "ktx2", "zstd_rust"] }
serde_json = "1.0.149"
base64 = "0.22.1"
phoenix-math = { path = "../phoenix-math" }
phoenix-platform = { path = "../phoenix-platform", features = ["audio"] }
