[global]
seed = 42

[[entity]]
template_path = "assets/entities/star_sun.toml"
position = [0.0, 0.0, 0.0]

[[entity]]
template_path = "assets/entities/planet_earth.toml"
id = "earth"
position = [200.0, 0.0, 200.0]

[[entity]]
template_path = "assets/entities/asteroid_field_main.toml"
position = [0.0, 0.0, 0.0]

[[entity]]
template_path = "assets/entities/player_ship.toml"
id = "player-ship"
position = [0.0, 0.0, 0.0]
spawn_on = "game_start"

[[entity]]
template_path = "assets/entities/region_nebula.toml"
id = "nebula-1"
position = [300.0, 0.0, -200.0]
