//! Explicit #1400 order of conflicting owners within each fixed phase.
//! Existing phase, run-condition and deferred-application boundaries remain
//! at their original registrations. These sets order execution only.
use bevy::prelude::*;

mod pass;
use pass::DeclaredOrder;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, SystemSet)]
pub(crate) enum FixedStep {
    LodAiShips,
    UnregisterOnDespawn,
    RegisterAiTokensOnSpawn,
    EmitPhaseChangeBalanceEvents,
    HeadlessAutoStart,
    EnforceFleetManagedCountdown,
    HandleDisconnect,
    HandleSetNameSystem,
    HandleReportStationEligibilitySystem,
    HandleSetStationRatingSystem,
    HandleSetAfkSystem,
    HandleSetSpectatorSystem,
    HandleSetReadySystem,
    HandleReleaseStationSystem,
    HandleSelectStationSystem,
    HandleIdentifySystem,
    TickCountdown,
    ApplyPendingStartGrants,
    UpdateGameStateCache,
    ReconcileRuntimeEntities,
    BroadcastWorldSetupOnStart,
    SimProcessingAnchor,
    RefreshCachesOnMidgameReconnect,
    DrainLobbyOutbox,
    CheckDestroyedAsteroids,
    UpdateAsteroidWindow,
    ReconcileStationPuppetControl,
    AdmitSystemCommands,
    AiTorpedoLoad,
    TickFrequencyHintHighFidelity,
    OperateCaptainAi,
    BackfillCaptainPrefersCinematicView,
    HandleSetRedAlert,
    HandleSetView,
    HandleSetObjectivePriority,
    ProjectActiveObjectiveStances,
    ReconcileStationStances,
    OperateCommandAi,
    HandleSetStationStance,
    ApplyAlertChangeToStances,
    ReconcileDirectedTargetControl,
    HandleStationRatingChange,
    HandleCoordinationEnqueue,
    AiPhaserAutoFire,
    TickWeaponsArcRequest,
    HandleSetPhaserMode,
    HandleSetPhaserFrequency,
    HandleSetTorpedoVolleyTarget,
    RevalidateGmFactionLocks,
    AiTargetSelection,
    HandleSetTarget,
    TickNpcAutoMatchFrequency,
    ApplyTacticalFrequencyHint,
    TickBlasterAutoFire,
    OperateExternalRepairAi,
    EmitShieldsCoordination,
    OperateSensorsAi,
    TickSensorsFrequencyHint,
    TickSensorsThreatWarning,
    OperateCivilianOrderAi,
    OperateCommsAi,
    ApplyHostLossBackfill,
    ResolveHumanSeekingHosts,
    EnforceStationPuppetControl,
    ApplyGodModeToggle,
    ApplyAssignedStationRating,
    RetireDialoguesForPendingLayerUnloads,
    HandleHail,
    OperateCommsResponseAi,
    HandleRespondToMessage,
    OperateTractorAi,
    OperateDockAi,
    OperateUmbilicalAi,
    OperateSecurityAi,
    OperateTransporterAi,
    TickCivilianTraffic,
    OperateDemolitionAi,
    HandleDemolitionCommands,
    HandleExternalRepairCommands,
    HandleClearComms,
    HandleShowOnScreen,
    HandleTractorCommands,
    HandleDockCommands,
    HandleUmbilicalCommands,
    HandleSecurityCommands,
    HandleTransporterCommands,
    PruneRepairRequestQueue,
    OperateRepairAi,
    HandleLoadTube,
    HandleUnloadTube,
    BuildTorpedoTargetSnapshot,
    HandleSensorsMessages,
    OperateNavigationAi,
    HandleNavigationWaypoint,
    IssueNavigateToClearance,
    AnchorMissionClock,
    ArmMissionDeadlines,
    ArmMissionWorkforces,
    ApplyPendingScenarioLoads,
    ApplyWorldLayerChanges,
    SimulateLowLodShips,
    HandleFireBlaster,
    TickBlasterSystem,
    TickTorpedoLifecycle,
    HandleDispatchRepairTeam,
    HandleRecallRepairTeam,
    HandleSetRepairPriority,
    HandleSetRepairTargetPriority,
    TickRepairTeams,
    HandleFirePhaser,
    UpdateRegionMembership,
    ApplyDamageZoneDamage,
    BuildWorldSnapshot,
    EmitAttackedOnNewAttacker,
    AiTorpedoAutoFire,
    AiPowerAllocation,
    AiShieldFocus,
    HandleFireTorpedo,
    HandleTorpedoMagazineInterSystem,
    HandlePowerMessages,
    TickPowerSystem,
    HandleShieldsMessages,
    CollectWorldEvents,
    TickTriggerPipeline,
    TickScriptCallbacks,
    OpenScriptedCommsThreads,
    TickDelayedActions,
    BuildHelmAiSurfacesFrame,
    AiPolicyStateTick,
    AiHelmLateralThrust,
    AiHelmImpulse,
    AiHelmVerticalThrust,
    AiHelmThrust,
    AiHelmBoost,
    AiHelmSteering,
    ProcessHelmInputs,
    TickImpulse,
    TickBoost,
    IntegrateShipPhysics,
    PublishJoystickToEngines,
    SyncShipPosition,
    OperateHelmEngineAi,
    ApplyGmDirectEffects,
    TickBeamsPrepare,
    HandleBlasterHits,
    HandleCollisions,
    DetectDamageTierCrossings,
    SyncConsoleDamageTiers,
    TickBeamsApplyDamage,
    TickBeamsTickLifetimes,
    TickExternalRepair,
    ApplyExternalRepair,
    TickPowerBrownoutAdvisory,
    DrainScriptedPowerOrders,
    MirrorWeaponsColdFlags,
    RefreshAnchoredWaypoint,
    TranslatePowerModifiers,
    TickShields,
    TranslateImpulseModifiers,
    ApplyRadarDamageModifiers,
    TickTractor,
    FinishTractorActionFeedback,
    MoveCoupledTarget,
    ApplyTowLoadPenalty,
    ArrestHeldDeclines,
    TickDock,
    TickUmbilical,
    TickInfrastructureCondition,
    FinishUmbilicalActionFeedback,
    TickSecurityTeams,
    RevealCivilianContacts,
    TickTransport,
    TickDebrisDrift,
    TickScans,
    AdvanceObjectiveCursors,
    FlushCoordinationPopups,
    PublishWeaponsCoreBlackboard,
    PublishTacticalRadarBlackboard,
    PublishPhaserBankBlackboards,
    PublishTorpedoTubeBlackboards,
    PublishTorpedoMagazineBlackboard,
    PublishRepairBlackboard,
    PublishPowerBlackboard,
    PublishShieldsBlackboard,
    PublishSensorsBlackboard,
    PublishSensorRadarBlackboard,
    PublishNavigationBlackboard,
    PublishCommsBlackboard,
    PublishTractorBlackboard,
    PublishDockBlackboard,
    PublishUmbilicalBlackboard,
    PublishSecurityBlackboard,
    RecordCivilianCasualties,
    PublishTransporterBlackboard,
    PublishDossierBlackboard,
    PublishScanBlackboard,
    PublishDemolitionBlackboard,
    PublishCommandBlackboard,
    PublishHelmBlackboard,
    PublishCaptainBlackboard,
    AggregateDoctrineBlackboards,
    PublishViewscreenBlackboard,
    ClearLastAttackerOnDeath,
    ClearLastAttackerOnRedAlertOff,
    BroadcastBlackboardUpdates,
    DetectReachedObjectiveCompletion,
    SettleStationPuppetFeedback,
    SettleRemovedStationFeedback,
    BroadcastCommsState,
    BroadcastObjectiveSummary,
    SimDispatch,
    UpdateCombatActivity,
    PublishScenarioState,
    EmitScenarioNarrative,
    EmitAuthoredAndMarkedEntityNarrative,
}

pub(crate) fn configure_fixed_order(app: &mut App) {
    use FixedStep::*;
    let mut order = DeclaredOrder::default();
    // LobbySystemSet: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            HandleSetNameSystem,
            HandleReportStationEligibilitySystem,
            HandleSetStationRatingSystem,
            HandleSetAfkSystem,
            HandleSetSpectatorSystem,
            HandleSetReadySystem,
            HandleReleaseStationSystem,
            HandleSelectStationSystem,
            HandleIdentifySystem,
        ],
    );
    // Input: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            AiTorpedoLoad,
            TickFrequencyHintHighFidelity,
            OperateCaptainAi,
            BackfillCaptainPrefersCinematicView,
            HandleSetRedAlert,
            HandleSetView,
            HandleSetObjectivePriority,
            ProjectActiveObjectiveStances,
            ReconcileStationStances,
            OperateCommandAi,
            HandleSetStationStance,
            ApplyAlertChangeToStances,
            ReconcileDirectedTargetControl,
            HandleStationRatingChange,
            HandleCoordinationEnqueue,
            AiPhaserAutoFire,
            TickWeaponsArcRequest,
            HandleSetPhaserMode,
            HandleSetPhaserFrequency,
            HandleSetTorpedoVolleyTarget,
            // A GM withdrawal of a hostility must drop stranded tactical locks
            // before the retention tier gets to keep one (issue #1442).
            RevalidateGmFactionLocks,
            AiTargetSelection,
            HandleSetTarget,
            TickNpcAutoMatchFrequency,
            ApplyTacticalFrequencyHint,
            TickBlasterAutoFire,
            OperateExternalRepairAi,
            EmitShieldsCoordination,
            OperateSensorsAi,
            TickSensorsFrequencyHint,
            TickSensorsThreatWarning,
            OperateCivilianOrderAi,
            OperateCommsAi,
            ApplyHostLossBackfill,
            ResolveHumanSeekingHosts,
            EnforceStationPuppetControl,
            ApplyGodModeToggle,
            ApplyAssignedStationRating,
            RetireDialoguesForPendingLayerUnloads,
            HandleHail,
            OperateCommsResponseAi,
            HandleRespondToMessage,
            OperateTractorAi,
            OperateDockAi,
            OperateUmbilicalAi,
            OperateSecurityAi,
            OperateTransporterAi,
            TickCivilianTraffic,
            OperateDemolitionAi,
            HandleDemolitionCommands,
        ],
    );
    // Input: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            HandleExternalRepairCommands,
            HandleTractorCommands,
            HandleDockCommands,
            HandleUmbilicalCommands,
            HandleSecurityCommands,
            HandleTransporterCommands,
        ],
    );
    // Physics: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            PruneRepairRequestQueue,
            OperateRepairAi,
            HandleLoadTube,
            HandleUnloadTube,
            HandleSensorsMessages,
            OperateNavigationAi,
            HandleNavigationWaypoint,
            IssueNavigateToClearance,
            AnchorMissionClock,
            ArmMissionDeadlines,
            ArmMissionWorkforces,
            ApplyPendingScenarioLoads,
            ApplyWorldLayerChanges,
            SimulateLowLodShips,
            HandleFireBlaster,
            TickBlasterSystem,
            TickTorpedoLifecycle,
            HandleDispatchRepairTeam,
            HandleRecallRepairTeam,
            HandleSetRepairPriority,
            HandleSetRepairTargetPriority,
            TickRepairTeams,
            HandleFirePhaser,
            UpdateRegionMembership,
            ApplyDamageZoneDamage,
            BuildWorldSnapshot,
            EmitAttackedOnNewAttacker,
            AiTorpedoAutoFire,
            AiPowerAllocation,
            AiShieldFocus,
            HandleFireTorpedo,
            HandleTorpedoMagazineInterSystem,
            HandlePowerMessages,
            TickPowerSystem,
            HandleShieldsMessages,
            CollectWorldEvents,
            TickTriggerPipeline,
            TickScriptCallbacks,
            OpenScriptedCommsThreads,
            TickDelayedActions,
            BuildHelmAiSurfacesFrame,
            AiPolicyStateTick,
            AiHelmLateralThrust,
            AiHelmImpulse,
            AiHelmVerticalThrust,
            AiHelmThrust,
            AiHelmBoost,
            AiHelmSteering,
            ProcessHelmInputs,
            IntegrateShipPhysics,
            PublishJoystickToEngines,
            SyncShipPosition,
            OperateHelmEngineAi,
        ],
    );
    // Physics: reviewed conflicting owner sequence.
    sequence(&mut order, &[TickImpulse, TickBoost]);
    // Damage: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            ApplyGmDirectEffects,
            TickBeamsPrepare,
            HandleBlasterHits,
            HandleCollisions,
            DetectDamageTierCrossings,
            SyncConsoleDamageTiers,
            TickBeamsApplyDamage,
            TickBeamsTickLifetimes,
        ],
    );
    // Modifiers: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            TickExternalRepair,
            TickPowerBrownoutAdvisory,
            DrainScriptedPowerOrders,
            MirrorWeaponsColdFlags,
            RefreshAnchoredWaypoint,
            TranslatePowerModifiers,
            TickShields,
            TranslateImpulseModifiers,
            ApplyRadarDamageModifiers,
            TickTractor,
            FinishTractorActionFeedback,
            MoveCoupledTarget,
            ApplyTowLoadPenalty,
            TickDock,
            TickUmbilical,
            TickInfrastructureCondition,
            FinishUmbilicalActionFeedback,
            TickSecurityTeams,
            RevealCivilianContacts,
            TickTransport,
            TickDebrisDrift,
            TickScans,
            AdvanceObjectiveCursors,
        ],
    );
    // Modifiers: reviewed conflicting owner sequence.
    sequence(&mut order, &[ApplyExternalRepair, ArrestHeldDeclines]);
    // Publish: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            PublishWeaponsCoreBlackboard,
            PublishTacticalRadarBlackboard,
            PublishPhaserBankBlackboards,
            PublishTorpedoTubeBlackboards,
            PublishTorpedoMagazineBlackboard,
            PublishRepairBlackboard,
            PublishPowerBlackboard,
            PublishShieldsBlackboard,
            PublishSensorsBlackboard,
            PublishSensorRadarBlackboard,
            PublishNavigationBlackboard,
            PublishCommsBlackboard,
            PublishTractorBlackboard,
            PublishDockBlackboard,
            PublishUmbilicalBlackboard,
            PublishSecurityBlackboard,
            RecordCivilianCasualties,
            PublishTransporterBlackboard,
            PublishDossierBlackboard,
            PublishScanBlackboard,
            PublishDemolitionBlackboard,
            PublishCommandBlackboard,
            PublishHelmBlackboard,
            PublishCaptainBlackboard,
        ],
    );
    // PublishAggregate: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            AggregateDoctrineBlackboards,
            PublishViewscreenBlackboard,
            ClearLastAttackerOnDeath,
            ClearLastAttackerOnRedAlertOff,
            BroadcastBlackboardUpdates,
        ],
    );
    // Broadcast: reviewed conflicting owner sequence.
    sequence(
        &mut order,
        &[
            DetectReachedObjectiveCompletion,
            SettleStationPuppetFeedback,
            SettleRemovedStationFeedback,
            BroadcastCommsState,
            BroadcastObjectiveSummary,
            SimDispatch,
            UpdateCombatActivity,
        ],
    );
    // Keep identity, lobby projection, output and streaming at their
    // captured pre-admission boundaries. Empty headless-only markers add no
    // systems or run conditions to native and browser hosts.
    order.before(UnregisterOnDespawn, RegisterAiTokensOnSpawn);
    order.before(
        RegisterAiTokensOnSpawn,
        crate::command_admission::AdmissionSet,
    );
    order.before(EmitPhaseChangeBalanceEvents, super::SimSet::Input);
    order.before(HeadlessAutoStart, crate::lobby::LobbySystemSet);
    order.before(
        BroadcastWorldSetupOnStart,
        crate::core::broadcast::ReconnectBoundary,
    );
    order.before(
        SimProcessingAnchor,
        crate::core::broadcast::ReconnectBoundary,
    );
    order.before(crate::core::broadcast::ReconnectBoundary, DrainLobbyOutbox);
    order.before(DrainLobbyOutbox, crate::command_admission::AdmissionSet);
    order.before(
        crate::core::broadcast::ReconnectBoundary,
        ReconcileStationPuppetControl,
    );
    order.before(crate::lobby::LobbySystemSet, CheckDestroyedAsteroids);
    order.before(
        crate::core::broadcast::ReconnectBoundary,
        CheckDestroyedAsteroids,
    );
    order.before(UpdateAsteroidWindow, super::SimSet::Input);
    order.before(PublishScenarioState, EmitScenarioNarrative);
    // Both owners queue entity changes for the same existing flush. Preserve
    // their application order even though Commands hides those component writes.
    order.before(UpdateRegionMembership, LodAiShips);
    app.init_schedule(FixedUpdate);
    let schedule = app.get_schedule_mut(FixedUpdate).unwrap();
    assert!(
        schedule.systems().is_err(),
        "fixed order must be installed before initialization"
    );
    assert!(schedule.get_build_settings().auto_insert_apply_deferred);
    // Schedule::default installs AutoInsertApplyDeferred first. Appending our
    // pass preserves the original sync semantics before adding execution edges.
    schedule.add_build_pass(order);
}

fn sequence(order: &mut DeclaredOrder, owners: &[FixedStep]) {
    for pair in owners.windows(2) {
        order.before(pair[0], pair[1]);
    }
}
