//! One reviewed native billboard bake. The child works only in an immutable
//! private stage; generated bytes do not enter the Workshop draft until the
//! page fetches, validates, and adopts them as one history transaction.
use crate::{
    delivery::{http, serve::HostedDocuments},
    entities::model_rig::ModelRig,
    workshop::provider::{safe_path, Files, Response},
};
use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::{Child, Command, Stdio},
};

const PREFIX: &str = "/workshop-billboard-capture/";

#[derive(Clone)]
struct Provenance {
    sidecar: String,
    lod: usize,
    source_revision: u64,
    output: String,
    source: String,
    yaw_views: u32,
    resolution: u32,
    pitch: f32,
}

struct ActiveCapture {
    id: String,
    stage: PathBuf,
    child: Option<Child>,
    routes: Vec<String>,
    paths: Vec<String>,
    candidates: BTreeSet<String>,
    provenance: Provenance,
}

pub struct BillboardCapture {
    documents: HostedDocuments,
    origin: String,
    directory: PathBuf,
    tool_root: PathBuf,
    executable: PathBuf,
    active: Option<ActiveCapture>,
}

impl BillboardCapture {
    pub fn new(
        documents: HostedDocuments,
        origin: String,
        tool_root: PathBuf,
        directory: PathBuf,
    ) -> Result<Self, String> {
        let current = std::env::current_exe().map_err(|error| error.to_string())?;
        let executable = current.with_file_name(if cfg!(windows) {
            "capture-billboard.exe"
        } else {
            "capture-billboard"
        });
        // The directory is capability-private and contains only disposable
        // stages. Clear a prior hard-exit residue before accepting a new view.
        remove_stage(&directory);
        fs::create_dir_all(&directory).map_err(|error| error.to_string())?;
        Ok(Self {
            documents,
            origin: origin.trim_end_matches('/').into(),
            directory,
            tool_root,
            executable,
            active: None,
        })
    }

    #[cfg(test)]
    fn with_executable(
        documents: HostedDocuments,
        directory: PathBuf,
        executable: PathBuf,
    ) -> Self {
        Self {
            documents,
            origin: "http://127.0.0.1:7".into(),
            directory,
            tool_root: std::env::current_dir().unwrap(),
            executable,
            active: None,
        }
    }

    #[allow(clippy::disallowed_methods)] // Private resource nonce, never simulation identity.
    pub fn start(
        &mut self,
        files: Files,
        sidecar: String,
        lod: usize,
        source_revision: u64,
    ) -> Result<Response, String> {
        self.retire();
        let text = files
            .get(&sidecar)
            .ok_or("Selected model sidecar is no longer in the draft")?;
        let text = std::str::from_utf8(text).map_err(|_| "Selected model sidecar is not UTF-8")?;
        let rig: ModelRig = toml::from_str(text)
            .map_err(|error| format!("Selected model sidecar is invalid: {error}"))?;
        let level = rig
            .lod
            .get(lod)
            .ok_or("Selected billboard LOD is no longer in the draft")?;
        let capture = level
            .capture
            .as_ref()
            .ok_or("Selected billboard LOD has no authored capture metadata")?;
        let output = level
            .billboard
            .as_deref()
            .ok_or("Selected capture does not name a billboard PNG")?;
        let source = capture
            .source
            .as_deref()
            .ok_or("Selected capture does not name a source GLB")?;
        let yaw_views = capture
            .yaw_views
            .filter(|value| *value > 0)
            .ok_or("Capture yaw_views must be positive")?;
        let resolution = capture
            .resolution
            .filter(|value| *value > 0)
            .ok_or("Capture resolution must be positive")?;
        let pitch = capture
            .pitch
            .filter(|value| value.is_finite())
            .ok_or("Capture pitch must be finite")?;
        if !runtime_model_path(output, ".png") || !runtime_model_path(source, ".glb") {
            return Err("Capture source/output must be runtime model assets".into());
        }
        if !files.contains_key(source) {
            return Err("Capture source GLB is outside the reviewed draft".into());
        }

        let mut candidates = BTreeSet::from([
            output.to_owned(),
            "scripts/lod-capture-manifest.toml".to_owned(),
        ]);
        for (path, bytes) in &files {
            if !path.starts_with("assets/models/") || !path.ends_with(".model.toml") {
                continue;
            }
            if let Some(other) = std::str::from_utf8(bytes)
                .ok()
                .and_then(|text| toml::from_str::<ModelRig>(text).ok())
            {
                if other
                    .lod
                    .iter()
                    .any(|item| item.billboard.as_deref() == Some(output) && item.capture.is_some())
                {
                    candidates.insert(path.clone());
                }
            }
        }
        let id = uuid::Uuid::new_v4().to_string();
        let stage = self.directory.join(&id);
        fs::create_dir_all(&stage).map_err(|error| error.to_string())?;
        let staged = (|| {
            for (path, bytes) in &files {
                let target = stage.join(path.replace('/', std::path::MAIN_SEPARATOR_STR));
                if let Some(parent) = target.parent() {
                    fs::create_dir_all(parent).map_err(|error| error.to_string())?;
                }
                fs::write(target, bytes).map_err(|error| error.to_string())?;
            }
            fs::create_dir_all(stage.join("scripts")).map_err(|error| error.to_string())?;
            let script = self.tool_root.join("scripts/capture-billboards.mjs");
            let mut command = Command::new("node");
            command
                .current_dir(&stage)
                .arg(script)
                .arg(output)
                .env("PHOENIX_CAPTURE_BIN", &self.executable)
                .env("PHOENIX_CAPTURE_OUTPUT", output)
                .stdin(Stdio::null())
                .stdout(Stdio::piped())
                .stderr(Stdio::piped());
            #[cfg(unix)]
            {
                use std::os::unix::process::CommandExt;
                command.process_group(0);
            }
            let child = command
                .spawn()
                .map_err(|error| format!("Billboard capture tool is unavailable: {error}"))?;
            Ok::<_, String>(child)
        })();
        let child = match staged {
            Ok(child) => child,
            Err(error) => {
                remove_stage(&stage);
                return Err(error);
            }
        };
        self.active = Some(ActiveCapture {
            id: id.clone(),
            stage,
            child: Some(child),
            routes: Vec::new(),
            paths: Vec::new(),
            candidates,
            provenance: Provenance {
                sidecar,
                lod,
                source_revision,
                output: output.into(),
                source: source.into(),
                yaw_views,
                resolution,
                pitch,
            },
        });
        Ok(self.response("running"))
    }

    pub fn status(&mut self) -> Result<Response, String> {
        let Some(active) = self.active.as_mut() else {
            return Err("No billboard capture is active".into());
        };
        if !active.routes.is_empty() {
            return Ok(self.response("ready"));
        }
        let Some(child) = active.child.as_mut() else {
            return Err("Billboard capture has no process".into());
        };
        let status = match child.try_wait() {
            Ok(Some(status)) => status,
            Ok(None) => return Ok(self.response("running")),
            Err(error) => {
                let message = error.to_string();
                self.retire();
                return Err(message);
            }
        };
        let child = active.child.take().unwrap();
        let output = match child.wait_with_output() {
            Ok(output) => output,
            Err(error) => {
                let message = error.to_string();
                self.retire();
                return Err(message);
            }
        };
        if !status.success() {
            let detail = String::from_utf8(output.stderr).unwrap_or_default();
            self.retire();
            return Err(if detail.trim().is_empty() {
                format!("Billboard capture failed ({status})")
            } else {
                format!("Billboard capture failed: {}", detail.trim())
            });
        }
        let base = format!("{PREFIX}{}/", active.id);
        for path in &active.candidates {
            let file = active
                .stage
                .join(path.replace('/', std::path::MAIN_SEPARATOR_STR));
            let bytes = match fs::read(&file) {
                Ok(bytes) => bytes,
                Err(error) => {
                    let message =
                        format!("Billboard capture produced an incomplete review: {path}: {error}");
                    self.retire();
                    return Err(message);
                }
            };
            if path == &active.provenance.output && !png_signature(&bytes) {
                self.retire();
                return Err("Billboard capture produced an invalid PNG".into());
            }
            let route = format!("{base}{}", active.paths.len());
            self.documents
                .publish_bytes(route.clone(), bytes, http::content_type_for(path), true);
            active.routes.push(route);
            active.paths.push(path.clone());
        }
        Ok(self.response("ready"))
    }

    pub fn cancel(&mut self) -> Response {
        self.retire();
        Response::Done
    }

    fn response(&self, state: &str) -> Response {
        let active = self
            .active
            .as_ref()
            .expect("response requires active capture");
        let p = &active.provenance;
        Response::BillboardCapture {
            capture: active.id.clone(),
            state: state.into(),
            image_url: active
                .paths
                .iter()
                .position(|path| path == &p.output)
                .map(|index| format!("{}{PREFIX}{}/{index}", self.origin, active.id)),
            output: Some(p.output.clone()),
            sidecar: Some(p.sidecar.clone()),
            lod: Some(p.lod),
            source_revision: Some(p.source_revision),
            source: Some(p.source.clone()),
            yaw_views: Some(p.yaw_views),
            resolution: Some(p.resolution),
            pitch: Some(p.pitch),
            base_url: (!active.routes.is_empty())
                .then(|| format!("{}{PREFIX}{}/", self.origin, active.id)),
            paths: active.paths.clone(),
        }
    }

    pub fn retire(&mut self) {
        if let Some(mut active) = self.active.take() {
            if let Some(mut child) = active.child.take() {
                terminate_tree(&mut child);
            }
            for route in active.routes {
                self.documents.withdraw(&route);
            }
            remove_stage(&active.stage);
        }
    }
}

fn png_signature(bytes: &[u8]) -> bool {
    bytes.starts_with(b"\x89PNG\r\n\x1a\n")
}
fn runtime_model_path(path: &str, suffix: &str) -> bool {
    safe_path(path) && path.starts_with("assets/models/") && path.ends_with(suffix)
}

#[cfg(test)]
#[allow(clippy::disallowed_methods, clippy::items_after_test_module)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn capture_paths_are_confined_runtime_model_members() {
        assert!(runtime_model_path("assets/models/ship.png", ".png"));
        assert!(runtime_model_path("assets/models/ship.glb", ".glb"));
        assert!(!runtime_model_path(
            "assets/models/../../../../target.png",
            ".png"
        ));
        assert!(!runtime_model_path("C:/target.png", ".png"));
        assert!(!runtime_model_path("assets/worlds/target.png", ".png"));
    }

    #[test]
    fn authored_output_traversal_is_refused_before_a_tool_can_start() {
        let directory = std::env::temp_dir().join(format!(
            "phoenix-billboard-path-test-{}",
            uuid::Uuid::new_v4()
        ));
        fs::create_dir_all(&directory).unwrap();
        let sidecar = "assets/models/ship.model.toml";
        let source = "assets/models/ship.glb";
        let files = BTreeMap::from([
            (source.into(), vec![1, 2, 3]),
            (sidecar.into(), format!(
                "[[lod]]\nbillboard='assets/models/../../../../target.png'\n[lod.capture]\nsource='{source}'\nyaw_views=8\nresolution=64\npitch=20\n"
            ).into_bytes()),
        ]);
        let mut capture = BillboardCapture::with_executable(
            HostedDocuments::default(),
            directory.clone(),
            directory.join("unused-capture-tool"),
        );
        assert!(capture
            .start(files, sidecar.into(), 0, 0)
            .unwrap_err()
            .contains("runtime model assets"));
        assert!(directory.read_dir().unwrap().next().is_none());
        let _ = fs::remove_dir_all(directory);
    }

    #[test]
    fn cancellation_stops_the_capture_descendant_before_removing_its_stage() {
        let stage = std::env::temp_dir().join(format!(
            "phoenix-billboard-cancel-test-{}",
            uuid::Uuid::new_v4()
        ));
        fs::create_dir_all(&stage).unwrap();
        let marker = stage.join("descendant.txt");
        let descendant =
            "setInterval(()=>require('fs').appendFileSync(process.env.PHOENIX_TEST_MARKER,'x'),20)";
        let parent = format!(
            "require('child_process').spawn(process.execPath,['-e',{}],{{stdio:'ignore',env:process.env}});setInterval(()=>{{}},1000)",
            serde_json::to_string(descendant).unwrap()
        );
        let mut command = Command::new("node");
        command
            .args(["-e", &parent])
            .env("PHOENIX_TEST_MARKER", &marker)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null());
        #[cfg(unix)]
        {
            use std::os::unix::process::CommandExt;
            command.process_group(0);
        }
        let mut child = command.spawn().unwrap();
        std::thread::sleep(std::time::Duration::from_millis(250));
        terminate_tree(&mut child);
        let before = fs::metadata(&marker).map(|value| value.len()).unwrap_or(0);
        assert!(before > 0, "the capture descendant never started");
        std::thread::sleep(std::time::Duration::from_millis(150));
        let after = fs::metadata(&marker).map(|value| value.len()).unwrap_or(0);
        assert_eq!(
            before, after,
            "the capture descendant survived cancellation"
        );
        remove_stage(&stage);
        assert!(!stage.exists());
    }
}
fn remove_stage(stage: &Path) {
    let _ = fs::remove_dir_all(stage);
}

fn terminate_tree(child: &mut Child) {
    #[cfg(windows)]
    {
        if let Ok(mut killer) = Command::new("taskkill")
            .args(["/PID", &child.id().to_string(), "/T", "/F"])
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
        {
            if !wait_bounded(&mut killer, std::time::Duration::from_secs(2)) {
                let _ = killer.kill();
            }
        }
    }
    #[cfg(unix)]
    {
        if let Ok(mut killer) = Command::new("kill")
            .args(["-KILL", &format!("-{}", child.id())])
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
        {
            if !wait_bounded(&mut killer, std::time::Duration::from_secs(2)) {
                let _ = killer.kill();
            }
        }
    }
    if !wait_bounded(child, std::time::Duration::from_secs(2)) {
        let _ = child.kill();
        wait_bounded(child, std::time::Duration::from_secs(2));
    }
}

fn wait_bounded(child: &mut Child, timeout: std::time::Duration) -> bool {
    let deadline = std::time::Instant::now() + timeout;
    loop {
        match child.try_wait() {
            Ok(Some(_)) => return true,
            Err(_) => return false,
            Ok(None) if std::time::Instant::now() < deadline => {
                std::thread::sleep(std::time::Duration::from_millis(10));
            }
            Ok(None) => return false,
        }
    }
}

impl Drop for BillboardCapture {
    fn drop(&mut self) {
        self.retire();
    }
}
