//! The `plog!` family.
//!
//! Each macro checks [`LogFilterConfig`] first and only then delegates to the
//! matching `bevy::log` macro with the category as its `target:`. Because the
//! format arguments live inside the `if`, a suppressed call site costs one hash
//! lookup plus a branch and never touches `format_args!`.
//!
//! Both a global and an entity-scoped form exist:
//!
//! ```ignore
//! pwarn!(log, LogCat::World, "scenario {path} missing");
//! pdebug!(log, LogCat::Admit, entity = ship, "rejected {system:?}");
//! ```
//!
//! `$cfg` may be a `Res<LogFilterConfig>`, a `&LogFilterConfig`, or the value
//! itself — it is only ever used through auto-deref.

/// Shared gate. Not called directly; use the level aliases below.
#[doc(hidden)]
#[macro_export]
macro_rules! __plog_gated {
    // Entity-scoped: both the category level and the entity allow-list apply.
    ($cfg:expr, $cat:expr, $level:expr, $emit:ident, entity = $entity:expr, $($arg:tt)*) => {{
        let __cfg = $crate::logging::AsLogFilter::log_filter(&$cfg);
        if __cfg.cat_enabled($cat, $level) && __cfg.entity_allowed($entity) {
            ::bevy::log::$emit!(target: $cat.target(), $($arg)*);
        }
    }};
    // Global: category level only. Always passes the entity filter, because an
    // event with no entity has nothing to filter on.
    ($cfg:expr, $cat:expr, $level:expr, $emit:ident, $($arg:tt)*) => {{
        let __cfg = $crate::logging::AsLogFilter::log_filter(&$cfg);
        if __cfg.cat_enabled($cat, $level) {
            ::bevy::log::$emit!(target: $cat.target(), $($arg)*);
        }
    }};
}

// The five level aliases. Written out rather than generated by a
// macro-defining-macro: nesting `macro_rules!` requires escaping every inner
// `$`, which makes the definition far harder to read than the repetition it
// saves. In each pair the entity arm must come first, otherwise the global arm
// would match `entity = ...` as the start of the format arguments.

/// Category-filtered `error!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! perror {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Error, error, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Error, error, $($arg)*)
    };
}

/// Category-filtered `warn!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! pwarn {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Warn, warn, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Warn, warn, $($arg)*)
    };
}

/// Category-filtered `info!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! pinfo {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Info, info, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Info, info, $($arg)*)
    };
}

/// Category-filtered `debug!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! pdebug {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Debug, debug, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Debug, debug, $($arg)*)
    };
}

/// Category-filtered `trace!`. See the [module docs](self) for the two forms.
#[macro_export]
macro_rules! ptrace {
    ($cfg:expr, $cat:expr, entity = $entity:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Trace, trace, entity = $entity, $($arg)*)
    };
    ($cfg:expr, $cat:expr, $($arg:tt)*) => {
        $crate::__plog_gated!($cfg, $cat, $crate::logging::LevelFilter::Trace, trace, $($arg)*)
    };
}

#[cfg(test)]
#[path = "macros_tests.rs"]
mod tests;
