name = "Cosmetic Asteroid 1"
tags = ["asteroid", "cosmetic"]

[collider]
shape = "Ball"
radius = 1
length = 0.0

[mesh]
model = "assets/models/asteroid_common_1_cosmetic.glb"
shape = "sphere"
radius = 1
colour = [0.5, 0.45, 0.38]
