name = "Small Asteroid 4"
tags = ["asteroid", "gameplay", "small"]

[target]
tags = ["asteroid"]
threat_level = "none"

[collider]
shape = "Ball"
radius = 2
length = 0.0

[hull]
hull_integrity = 30

[mesh]
model = "assets/models/asteroid_common_4_small.glb"
shape = "sphere"
radius = 2
colour = [0.55, 0.5, 0.42]
