name = "Cosmetic Asteroid 4"
tags = ["asteroid", "cosmetic"]

[collider]
shape = "Ball"
radius = 1
length = 0.0

[mesh]
model = "assets/models/asteroid_common_4.glb"
variant = "cosmetic"
shape = "sphere"
radius = 1
colour = [0.5, 0.45, 0.38]
