name = "Earth"
tags = ["planet", "habitable"]

[target]
tags = ["planet"]
threat_level = "none"
description = "Earth"

[collider]
shape = "Ball"
radius = 20.0
length = 0.0

[radar_appearance]
colour = [0.0, 0.6, 1.0]
radius = 20.0
icon = "planet"

[mesh]
model = "assets/models/planet_paradise.glb"
shape = "sphere"
radius = 20.0
colour = [0.0, 0.5, 1.0]
