name = "Nebula"
tags = ["region", "nebula"]

[target]
tags = ["region"]
threat_level = "none"
description = "Nebula region"

[shape]
type = "sphere"
radius = 150.0

[effects]
[effects.comms_jammed]
[effects.sensor_blind]
