name = "entity.region_nebula.name"
tags = ["region", "nebula"]

[radar_appearance]
region_colour = [0.6, 0.4, 1.0]

[target]
tags = ["region"]
threat_level = "none"
description = "entity.region_nebula.target.description"

[shape]
type = "sphere"
radius = 150.0

[effects]
[effects.comms_jammed]
[effects.sensor_blind]
