import { readFile, access } from 'node:fs/promises';
import path from 'node:path';
import { parse } from 'smol-toml';
import { validateSoundCatalog, SOUND_CUES_PATH, SOUND_CUES_JSON } from '../gui/sound-cues.js';
export { SOUND_CUES_JSON };
export const SOUND_CUE_INVENTORY='gui/sound-cue-inventory.js';
export async function soundCueInventoryJs(root) {
  const value=parse(await readFile(path.join(root,SOUND_CUES_PATH),'utf8'));
  return '// Generated by scripts/sound-cues.mjs from the shipped catalogue.\nexport default '+JSON.stringify(value.assets,null,2)+';\n';
}
export async function soundCuesJson(root) {
  const value=parse(await readFile(path.join(root,SOUND_CUES_PATH),'utf8'));
  const checked=validateSoundCatalog(value,value.assets);
  if (checked.findings.length) throw new Error(JSON.stringify(checked.findings));
  for (const asset of value.assets) await access(path.join(root,asset.file));
  return JSON.stringify(value,null,2)+'\n';
}
