[[preset]]
name = "Low"
hidden_elements = ["power_overflow_controls"]

[preset.ai]
movement_rule = { thrust_threshold = 0.7, engage_delay_secs = 3.0, battery_engage_min_pct = 50.0, battery_recharge_pct = 100.0 }
red_alert_rule = { engage_delay_secs = 3.0, battery_engage_min_pct = 10.0, battery_recharge_pct = 100.0 }

[[preset]]
name = "Std"
hidden_elements = []
